### ISSUE TITLE
[v0.9.0] Main tracker

### ISSUE THREAD

**Issue by OrigamingWasTaken** [AppleBlox/appleblox#53]
This is an updated list of things I want to add in AppleBlox v0.9.0.

### Bug Fixes
- [x] Add an option to use osascript notifications if alerter doesn't work
- [x] Fix broken mods installation (leftovers)
- [x] Fix broken font installation (leftovers)
- [x] Remove outdated presets and re-add old ones (ex: FPS cap)
- [x] Fix MacOS code-signing issues
> For mods, AppleBlox sets the "NSHighResolution" inside Roblox's plist file, which sometimes prevent the app from starting correctly
- [x] Fix small DiscordRPC formatting issues
- [x] Fix server location spam (idk but we'll find how)

### Features
- [x] Proper customizable bootstrapper popup (like Bloxstrap)
- [x] Flags editor overhaul
> Check flags validity on app startup, and display a better looking popup with options to delete invalid flags. Use [flagsman](https://github.com/AppleBlox/flagsman), which is an optimized fast-flags tracker written in Python, for AppleBlox.
- [x] Re-implement some presets like the FPS Cap
- [x] Better onboarding popup
- [ ] Emoji support
- [x] ~~Feature to change the app icon to a custom image, or a preset~~ (canceled, would make the app binary too large and is too complicated to implement)

**Comment by ok-coder1** [comment]
> canceled, would make the app binary too large and is too complicated to implement

It is possible to use a dependency called `fileicon` and make AppleBlox call a bash script which runs it, but I do feel like this might create some issues.
